#%RAML 1.0 SecurityScheme
type: x-client-enforcement
displayName: Client ID Enforcement
describedBy:
  headers:
    client_id:
      type: string
      required: true
      example: s49402srr93s49402srr93we
    client_secret:
      type: string
      required: true
      example: wklsmnxcvwklsmnxcvrt48f1
  responses:
    401:
      body:
        application/json:
          properties:
            error:
              type: string
              description: A description of the error.
              example: Client Credentials Invalid
          example: |
            {
              "error": "Client Credentials Invalid"
            }